### ISSUE TITLE
redeeming a channel is possible even after its expiration

### ISSUE THREAD

**Issue by takahser** [Trinkler/trade-htlcs#13]
Please provide the following information:

### Expected behaviour
Redeeming a channel is only possible, as long the channel is not expired.

### Actual behaviour
Redeeming seems to be possible whenever the state matches.
While the `refundChannel` features such a [check](https://github.com/Trinkler/agora-htlcs/blob/master/src/Htlc.sol#L267), the `redeemChannel` [lacks](https://github.com/Trinkler/agora-htlcs/blob/master/src/Htlc.sol#L235) a timelock guard.

**Comment by takahser** [comment]
Ok let's think this through properly.

1. Let's assume, Alice opens the channel 1 on asset 1, 24h, with Bob as the receiver.
2. Bob immediately opens the channel 2 on asset 2, 12h, with Alice as the receiver.
3. Alice waits 25h, makes a refund on Asset1.
4. Alice immediately after redeems the second channel on Asset2.

=> Bob ends up with neither the assets from Chain1 nor Chain2.

**So, can we prevent that?**

We could add checks to the redeem logic in the participate channel to assure that Alice cannot redeem asset 2 from channel 2 after the timelock expires. In other words, at any given time, it's either possible to refund OR redeem, but not both at any given time.

**How can we implement that?**

In the case of ETH, it's probably as simple as adding:

```
function redeemChannel(bytes32 channelId, bytes32 secret)
  public
  {
    require(now < channels[channelId].expiresAt, "TOO_LATE");
```

**Comment by retotrinkler** [comment]
#### Counter-example

It goes both ways. 
In above scenario and with the redeem restriction there is also the possibility of:

1. Let's assume, Alice opens the channel 1 on asset 1, 24h, with Bob as the receiver.
2. Bob immediately opens the channel 2 on asset 2, 12h, with Alice as the receiver.
3. Bob waits 13h, for his channel to expire and makes a redeem on Asset1. **Assumption: Alice didn't already redeem in time**.
4. Alice now can't redeem Bobs channel anymore due to the time restriction

=> Bob ends up with both the assets from Chain1 and Chain2.

#### How can we prevent this?

1. Let's assume, Alice opens the channel 1 on asset 1, 12h timeout, with Bob as the receiver.
2. Bob within 1hr (enforced by the frontend and api) opens the channel 2 on asset 2, 1hr timeout, with Alice as the receiver.
3. Alice now only has 1hr to redeem the channel. In case she does not the API triggers the refund to Bob. **Assumption: API available and monitoring trade**.
4. Bob has 10h window to redeem the second channel.

**Comment by takahser** [comment]
> It goes both ways.

The reverse way (Bob redeeming before Alice) is in reality very unlikely, since Bob won't know the secret, as long as Alice hasn't redeemed, yet.

> Bob has 10h window to redeem the second channel.

I agree it's sufficient for a first version and should generally work, as long as the exchange fulfills her duty of submitting the delegateRedeem transaction. But it would still be safer, if the HTLCs checked the condition, if the channel is still active when redeeming. I don't see any drawback, except the moderate additional effort it takes to code this enhancement.

**Comment by retotrinkler** [comment]
> The reverse way (Bob redeeming before Alice) is in reality very unlikely, since Bob won't know the secret, as long as Alice hasn't redeemed, yet.

True.

> But it would still be safer, if the HTLCs checked the condition, if the channel is still active when redeeming. I don't see any drawback, except the moderate additional effort it takes to code this enhancement.

Agree.
